name: "fetch"
on:
  push:
    branches:
      - main
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rover fetch
      id: fetch
      uses: ./
      with:
        graph: rover-actions
        variant: current
        federated: true
        subgraph: products
      env:
        APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
  artifact:
    needs: fetch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: products.graphql
    - run: cat products.graphql